version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_Fiap
    ports:
      - "27017:27017"
    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: streamingvideofiap_db

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
